openapi: 3.0.1
info:
  title: IBM Aspera faspio Gateway API
  description: API for IBM Aspera faspio Gateway Management
  contact:
    name: IBM Aspera
    email: Aspera-client-team@wwpdl.vnet.ibm.com
  license:
    name: (c) IBM. All rights reserved
    url: >-
      https://www-40.ibm.com/software/sla/sladb.nsf/displaylis/0CF8A1C0BA2B994C002587F70069A8B5?OpenDocument
  version: 1.0.0
externalDocs:
  description: IBM Aspera faspio Gateway Documentation
  url: https://www.ibm.com/docs/en/faspio-gateway
tags:
  - name: /bridges
paths:
  /bridges:
    get:
      tags:
        - /bridges
      summary: Get a Listing of All Bridges
      description: Retrieve a listing of all configured bridges.
      operationId: getBridges
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/bridges_response'
        '401':
          description: Unauthorized
    post:
      tags:
        - /bridges
      summary: Create a New Bridge
      description: Create a new bridge.
      operationId: addBridge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bridges_params'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/bridges_response'
        '401':
          description: Unauthorized
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
      x-codegen-request-body-name: body
  /bridges/{id}:
    get:
      tags:
        - /bridges
      summary: Get Information on a Specific Bridge
      description: Retrieve information on a specific bridge.
      operationId: getBridgeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bridges_response'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
    delete:
      tags:
        - /bridges
      summary: Delete a Specific Bridge
      description: Delete a specific bridge.
      operationId: deleteBridgeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
servers:
  - url: http://127.0.0.1:8080
security:
  - basicAuth: []
  - bearerAuth: []
  - {}
components:
  schemas:
    bridges_params:
      required:
        - name
        - local
        - forward
      type: object
      properties:
        forward:
          type: object
          required:
            - port
            - protocol
            - tls_enabled
          properties:
            host:
              type: array
              items:
                type: string
              example:
                - GW2
                - 10.0.0.2
            bind_address:
              type: string
              example: 127.0.0.1
            port:
              type: string
              example: 3000-3001
            protocol:
              type: string
              example: fasp
            tls_enabled:
              type: boolean
              example: false
        local:
          type: object
          required:
            - bind_address
            - port
            - protocol
            - tls_enabled
          properties:
            bind_address:
              type: string
              example: 127.0.0.1
            port:
              type: string
              example: 2000-2001
            protocol:
              type: string
              example: tcp
            tls_enabled:
              type: boolean
              example: false
        name:
          type: string
          example: Bridge-1
    bridges_response:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Bridge-1
        local:
          type: object
          properties:
            bind_address:
              type: string
              example: 127.0.0.1
            ports:
              type: array
              items:
                type: integer
              example:
                - 2000
                - 2001
            protocol:
              type: string
              example: tcp
            tls_enabled:
              type: boolean
              example: false
        forward:
          type: object
          properties:
            bind_address:
              type: string
              example: 127.0.0.1
            hosts:
              type: array
              items:
                type: string
              example:
                - GW2
                - 10.0.0.2
            ports:
              type: array
              items:
                type: integer
              example:
                - 3000
                - 3001
            protocol:
              type: string
              example: fasp
            tls_enabled:
              type: boolean
              example: false
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        Consult the documentation for requesting a JWT bearer token from the
        server.
