# frozen_string_literal: true

source 'https://rubygems.org/'

gem 'aspera-cli', '~> 4.21.1'
gem "grpc-tools"                # For gRPC code generation
gem "grpc"                      # For gRPC support
gem "google-protobuf"           # For Protobuf support
gem "rake"                      # Commonly used for build tasks