# frozen_string_literal: true

source 'https://rubygems.org/'

gem 'base64'
gem 'google-protobuf'           # For Protobuf support
gem 'grpc'                      # For gRPC support
gem 'grpc-tools'                # For gRPC code generation
gem 'jwt'
gem 'rake'                      # Commonly used for build tasks
gem 'rest-client'
