# paths of files and folder
# specified relative to the project main folder

# variable values, server addresses, credentials, etc...
main_config: private/config.yaml
sdk_runtime: tmp/transfer_sdk
sdk_samples: tmp/transfer_sdk/connectors
proto: tmp/transfer_sdk/connectors/grpc/transfer.proto
temp: tmp
