# paths of files and folder
# specified relative to the project main folder
main_config: private/config.yaml
temp: tmp
sdk_runtime: tmp/sdk_runtime
sdk_dev: tmp/sdk_dev
proto: tmp/sdk_dev/connectors/grpc/transfer.proto
