# paths of files and folder relative to the project main folder
main_config: private/config.yaml
temp_gene: generated
sdk_root: generated/trsdk
trsdk_noarch: generated/trsdk/noarch
proto: generated/trsdk/noarch/connectors/grpc/transfer.proto
